# Generated by Django 5.2.17 on 2026-10-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="last_donated",
            field=models.DateField(blank=True, null=True),
        ),
    ]
